Create readMe.md
derricka83/KXM_Web3_Business_Application_Marketplace_ENT- pull request #2
Opened 2023-12-03 19:57 UTC by ReaxonTV

I created the table of content for the documentation. I will insert the detailed documentation of each chapter in the next few weeks (currently very busy), but I already felt to share the current state of work with you. If you want, you can also already start documenting, otherwise I will do in the next few weeks.

2023-12-09 16:04 UTC, ReaxonTV commented
Can you accept the pull request or give me feedback if not okay? Thanks :)

2024-01-08 20:46 UTC, derricka83 approved these changes
Thank you will be reviewing and merging soon

2024-01-08 20:46 UTC, merged

2024-05-01 17:07 UTC, derricka83 approved these changes

2025-08-19 15:30 UTC, derricka83 requested changes
Charms Change Request

Requester: @derricka83 
Change Title: Update Documentation Reference

Current Documentation:

Mentions “get from a date and site”


Requested Change: 

Update reference to: “QhySync QoS Platform with vRAN & qRAN Technology”


Reason for Change:

To align documentation with the new mobile network site platform under QhySync.


Impact:

Ensures consistency across all technical and business documentation

Clarifies branding and technology stack (QoS, vRAN, qRAN).  This is all part of a much biggersystem 
@ReaxonTV